quantity = 'topo'
min_lat = 45
max_lat = 49
min_lon = 15
max_lon = 20
resolution = 1
shcs_data = "./input_data/DTM2006.mat"
resolution_unit = 'minutes'
nmin = 0
nmax = None
ellipsoid = 'GRS80'
#shcs_type = None
ref_surface_type = 'sphere'
height = 0
#ref_radius = None
GM = None
R = None
DTM_shcs_data = None
#DTM_shcs_type=None
output_file = './output/topo_test.nc'